name: plugin-spring-data
description: This plugin is used to create Spring Data configurations for Spring applications
display-name: plugin-spring-data
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Please, choose a data base type to apply into application
    type: text
    name: database_type
    items:
      - MySql
      - Sql Server
      - PostgreSql
  - label: Do you want to set a H2 memory database? Y (Yes) N (No)
    type: text
    name: has_memory_database
    items:
      - Y
      - N
  - label: Do you want to set migration with FlyWay? Y (Yes) N (No)
    type: text
    name: has_database_migration
    items:
      - Y
      - N
  - label: Inform the database url
    type: text
    name: database_url
  - label: Inform the database name
    type: text
    name: database_name
  - label: Inform the database username
    type: text
    name: database_username
  - label: Inform the database password
    type: text
    name: database_password

hooks:
  - type: edit
    trigger: after-render
    path: build.gradle
    condition:
      variable: database_type
      operator: ==
      value: MySql
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/mysql-dependency.gradle
          when:
            not-exists: snippets/mysql-dependency.gradle
  - type: edit
    trigger: after-render
    path: src/main/resources/application.properties
    condition:
      variable: database_type
      operator: ==
      value: MySql
    changes:
      - insert:
          line: 0
          snippet: snippets/mysql-config-application.properties
          when:
            not-exists: snippets/mysql-config-application.properties

  - type: edit
    trigger: after-render
    path: build.gradle
    condition:
      variable: database_type
      operator: ==
      value: Sql Server
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/sqlserver-dependency.gradle
          when:
            not-exists: snippets/sqlserver-dependency.gradle
  - type: edit
    trigger: after-render
    path: src/main/resources/application.properties
    condition:
      variable: database_type
      operator: ==
      value: Sql Server
    changes:
      - insert:
          line: 0
          snippet: snippets/sqlserver-config-application.properties
          when:
            not-exists: snippets/sqlserver-config-application.properties

  - type: edit
    trigger: after-render
    path: build.gradle
    condition:
      variable: database_type
      operator: ==
      value: PostgreSql
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/postgre-dependency.gradle
          when:
            not-exists: snippets/postgre-dependency.gradle
  - type: edit
    trigger: after-render
    path: src/main/resources/application.properties
    condition:
      variable: database_type
      operator: ==
      value: PostgreSql
    changes:
      - insert:
          line: 0
          snippet: snippets/postgre-config-application.properties
          when:
            not-exists: snippets/postgre-config-application.properties

  - type: edit
    trigger: after-render
    path: build.gradle
    condition:
      variable: has_memory_database
      operator: ==
      value: Y
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/h2-dependency.gradle
          when:
            not-exists: snippets/h2-dependency.gradle
  - type: edit
    trigger: after-render
    path: src/main/resources/application.properties
    condition:
      variable: has_memory_database
      operator: ==
      value: Y
    changes:
      - insert:
          line: -1
          snippet: snippets/h2-config-application.properties
          when:
            not-exists: snippets/h2-config-application.properties

  - type: edit
    trigger: after-render
    path: build.gradle
    condition:
      variable: has_database_migration
      operator: ==
      value: Y
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/flyway-dependency.gradle
          when:
            not-exists: snippets/flyway-dependency.gradle
  - type: render-templates
    trigger: after-render
    path: migration-directories
    condition:
      variable: has_database_migration
      operator: ==
      value: Y
