name: plugin-spring-data
description: This plugin is used to create Spring Data configurations for Spring applications
display-name: plugin-spring-data
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Input Example
    type: text
    name: example
    default: any text
  - label: Example of number
    type: int
    name: any_number
    default: "10"
  - label: Example of list
    type: multiselect
    name: any_list
    items:
      - item1
      - item2
