type: app
description: Default stackfile usecase description
# template used to create the project
template: stack-spring-base-applications/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: stack-spring-base-applications/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
